import React from 'react';
import type { Icon as PhosphorIcon, IconWeight } from 'phosphor-react-native';
import {
  CheckIcon,
  TicketIcon,
  BuildingIcon,
  MagnifyingGlassIcon,
  CaretLeftIcon,
  CaretDownIcon,
  CaretRightIcon,
  ArrowRightIcon,
  EyeIcon,
  EyeSlashIcon,
  BankIcon,
  ArrowUpRightIcon,
  ArrowDownLeftIcon,
  GiftIcon,
  QuestionIcon,
  BellIcon,
  GearIcon,
  InfoIcon,
  CopyIcon,
  ShareNetworkIcon,
BookmarkIcon,
MapTrifoldIcon,
  ListIcon,
  XCircleIcon,
  ClockIcon,
  SquaresFourIcon,
  HardHatIcon,
  TrayIcon,
  StarIcon,
  UserIcon,
  WarningCircleIcon,
  CheckCircleIcon,
  MapPinIcon,
  PhoneIcon,
  CalendarIcon,
  NavigationArrowIcon,
  UsersIcon,
  LightbulbIcon,
  FileTextIcon,
  HouseIcon,
  ChatCircleDotsIcon,
  ForkKnifeIcon,
  CarIcon,
  BriefcaseIcon,
  MegaphoneIcon,
  SparkleIcon,
  PaperPlaneTiltIcon,
  ShieldCheckIcon,
  WalletIcon,
  MicrophoneIcon,
  PlusIcon,
  MinusIcon,
} from 'phosphor-react-native';

const ICON_MAP: Record<string, PhosphorIcon> = {
  checkmark: CheckIcon,
  'chevron-forward': CaretRightIcon,
  'arrow-right': ArrowRightIcon,
  eye: EyeIcon,
  'eye-off': EyeSlashIcon,
  bank: BankIcon,
  'arrow-up-right': ArrowUpRightIcon,
  'arrow-down-left': ArrowDownLeftIcon,
  gift: GiftIcon,
  help: QuestionIcon,
  notifications: BellIcon,
  settings: GearIcon,
  info: InfoIcon,
  copy: CopyIcon,
  share: ShareNetworkIcon,
  bookmark: BookmarkIcon,
  'bookmark-outline': BookmarkIcon,
  map: MapTrifoldIcon,
  'map-outline': MapTrifoldIcon,
  list: ListIcon,
  'ticket-outline': TicketIcon,
  'business-outline': BuildingIcon,
  search: MagnifyingGlassIcon,
  'search-outline': MagnifyingGlassIcon,
  'chevron-back': CaretLeftIcon,
  'chevron-down': CaretDownIcon,
  'close-circle': XCircleIcon,
  'time-outline': ClockIcon,
  'grid-outline': SquaresFourIcon,
  'construct-outline': HardHatIcon,
  'file-tray-outline': TrayIcon,
  star: StarIcon,
  'person-outline': UserIcon,
  person: UserIcon,
  'alert-circle-outline': WarningCircleIcon,
  'checkmark-circle': CheckCircleIcon,
  'location-outline': MapPinIcon,
  'call-outline': PhoneIcon,
  'calendar-outline': CalendarIcon,
  'navigate-outline': NavigationArrowIcon,
  navigate: NavigationArrowIcon,
  add: PlusIcon,
  remove: MinusIcon,
  'people-outline': UsersIcon,
  'bulb-outline': LightbulbIcon,
  'document-text-outline': FileTextIcon,
  'document-text': FileTextIcon,
  home: HouseIcon,
  'home-outline': HouseIcon,
  chatbubble: ChatCircleDotsIcon,
  'chatbubble-outline': ChatCircleDotsIcon,
  restaurant: ForkKnifeIcon,
  'restaurant-outline': ForkKnifeIcon,
  car: CarIcon,
  'car-outline': CarIcon,
  briefcase: BriefcaseIcon,
  'briefcase-outline': BriefcaseIcon,
  megaphone: MegaphoneIcon,
  'megaphone-outline': MegaphoneIcon,
  sparkles: SparkleIcon,
  'sparkles-outline': SparkleIcon,
  'paper-plane-outline': PaperPlaneTiltIcon,
  'shield-checkmark': ShieldCheckIcon,
  'wallet-outline': WalletIcon,
  wallet: WalletIcon,
  mic: MicrophoneIcon,
  'mic-outline': MicrophoneIcon,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: any;
  weight?: IconWeight;
}

export const Icon: React.FC<IconProps> = ({ name, size = 22, color = '#000000', style, weight }) => {
  const PIcon = ICON_MAP[name] ?? ICON_MAP['briefcase-outline'];
  return <PIcon size={size} color={color} weight={weight ?? 'regular'} style={style} />;
};

export default Icon;